FROM golang:1.24.1-alpine AS builder

WORKDIR /app

COPY . .

RUN go mod tidy
RUN go mod download

RUN go build -o service ./src

FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/service .

EXPOSE 80

ENTRYPOINT ["./service"]








