[package]
name = "archive"
version = "0.1.0"
edition = "2021"

[dependencies]
flate2 = "1.0.30"
tar = "0.4.41"
tokio = { version = "1.38.1", features = ["fs", "time"] }
tokio-util = { version = "0.7.11", features = ["io", "io-util"] }
uuid = { version = "1.10.0", features = ["v4", "fast-rng"] }
