import_path: user_delete
description: "Simple CRUD operations for an user entity"
is_async: true
returns: true
depends_on:
  - name: db:mongo
    init: seed-user
signature:
  function: delete_user_by_id
  parameters:
    - arg: 0
      type: integer
      format: int64
      minimum: 1
      maximum: 3000000
