[build-system]
requires = ["setuptools>=63.0"]
build-backend = "setuptools.build_meta"

[project]
name = "primes"
description = "Simple function to generate prime numbers."
version = "1.0.0"
requires-python = ">=3.9"
