[package]
name = "copy"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.38.1", features = [
  "fs",
  "sync",
  "rt",
  "io-util",
  "time",
] }
uuid = { version = "1.10.0", features = ["v4", "fast-rng"] }
