[build-system]
requires = ["setuptools>=63.0"]
build-backend = "setuptools.build_meta"

[project]
name = "rng"
description = "Simple function to generate random numbers."
version = "1.0.0"
requires-python = ">=3.9"
