application: my_first_application
ssh:
  key_file: ~/.ssh/id_ed25519
  user_name: creo
  master_hosts:
    - 10.1.3.49
  worker_hosts:
    - 10.1.3.32
benchmark:
  warmup:
    rate: 5
    pause: 10
    duration: 30
  intensity:
    profile: getting_started.csv
  virtual_user: 200
  timeout: 8000
  records: 3000000
