application: matrix-benchmark
ssh:
  key_file: ~/.ssh/id_ed25519
  user_name: matthias
  master_hosts:
    - 10.1.3.43
  worker_hosts:
    - 10.1.3.43
benchmark:
  warmup:
    rate: 5
    pause: 10
    duration: 30
  intensity:
    profile: getting_started.csv
  virtual_user: 200
  timeout: 8000
  records: 30000
