# `name` specifies the name of the application.
# This will be used as the name of the output directory.
name: user-create-rs
seed: xfXAK0gC0WjUdXHp
# `mode` specifies the generation mode.
mode: manual
services:
  - name: user
    language: rust
    endpoints:
      - name: create
        function: user_create
