name: scaling-rust
mode: manual

services:
  - name: service1
    language: rust
    endpoints:
      - name: matrix
        function: matrix
        inter_service_calls:
          - service2.rng
          - service3.primes

  - name: service2
    language: rust
    endpoints:
      - name: rng
        function: rng

  - name: service3
    language: rust
    endpoints:
      - name: primes
        function: primes
