name: scaling-go
mode: manual

services:
  - name: service1
    language: go
    endpoints:
      - name: matrix
        function: matrix
        inter_service_calls:
          - service2.rng
          - service3.primes

  - name: service2
    language: go
    endpoints:
      - name: rng
        function: rng

  - name: service3
    language: go
    endpoints:
      - name: primes
        function: primes
