programming_language: python
application: profile-node
ssh_config:
  key_file: ~/.ssh/id_ed25519
  master_hosts:
    - 10.1.3.43
  worker_hosts:
    - 10.1.3.19
  user_name: matthias
benchmark:
  rps:
    - 25
    - 75
    - 150
  iterations: 5
  benchmark_duration: 900
  virtual_users: 600
  warmup_pause: 10
  warmup_duration: 120
  warmup_rps: 10
  timeout: 8000
  records: 3000000
