[build-system]
requires = ["setuptools>=63.0"]
build-backend = "setuptools.build_meta"

[project]
name = "hash"
description = "Simple function to hash a given password."
version = "1.0.0"
requires-python = ">=3.9"
dependencies = ["argon2-cffi>=23.1.0,<23.2.0"]
