import_path: user_update
description: "Simple CRUD operations for an user entity"
is_async: true
returns: true
depends_on:
  - name: db:mongo
    init: seed-user
signature:
  function: update_user_by_id
  parameters:
    - arg: 0
      type: integer
      format: int64
      minimum: 1
      maximum: 3000000
    - arg: 1
      type: object
      properties:
        username:
          type: string
          minLength: 3
          maxLength: 64
        email:
          type: string
          minLength: 3
          maxLength: 64
        password:
          type: string
          minLength: 6
          maxLength: 48
      additionalProperties: false
