import_path: delete_invoice
description: "Deletes an invoice from a MongoDB collection by its ID."
is_async: true
returns: true
depends_on:
  - name: db:mongo
    init: seed-invoice
signature:
  function: DeleteInvoiceByID
  parameters:
    - arg: 0
      type: integer
      minimum: 1
      maximum: 300000
